language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
script:
  - ./grabrepos.py
  - mkdocs build
branches:
  only:
    - master
deploy:
  provider: pages
  repo: homieiot/homieiot.github.io
  target-branch: master
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: site
  on:
    branch: master
