language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
script:
  - ./build.sh
branches:
  only:
    - master
deploy:
  provider: pages
  repo: https://github.com/homieiot/homieiot.github.io.git
  target-branch: master
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: site
  on:
    branch: master
