site_name: Homie MQTT Convention
site_description: The Homie convention strives to be a communication definition on top of MQTT between IoT devices and controlling entities.
theme:
  name: 'material'
  logo: 'banner.png'
  include_search_page: false
  search_index_only: true
  feature:
    tabs: true
  custom_dir : custom_theme
extra:
  repo_url_dest: 'https://github.com/homieiot/convention'
extra_css: [extra.css]
repo_url: 'https://github.com/homieiot/website-redesign'
edit_uri: 'edit/master/'
repo_name: 'homieiot/convention'
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - meta

